//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteTitular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteTitular()
        {
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
            this.Solicitudes = new HashSet<Solicitudes>();
            this.TarjetaDeCredito = new HashSet<TarjetaDeCredito>();
            this.TitularExtensiones = new HashSet<TitularExtensiones>();
        }
    
        public long Id { get; set; }
        public string DNIConyuge { get; set; }
        public string NombreConyuge { get; set; }
        public string ApellidoConyuge { get; set; }
        public int DNI { get; set; }
        public string CUIT { get; set; }
        public System.DateTime FechaDeNacimiento { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Nacionalidad { get; set; }
        public long EstadoCivilId { get; set; }
        public int Sexo { get; set; }
        public Nullable<decimal> IngresosMensuales { get; set; }
        public string Ocupacion { get; set; }
        public long DireccionId { get; set; }
        public int TelefonoCelular_CodigoArea { get; set; }
        public long TelefonoCelular_Numero { get; set; }
        public int TelefonoParticular_CodigoArea { get; set; }
        public long TelefonoParticular_Numero { get; set; }
        public System.Guid RowId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public Nullable<System.Guid> ChangedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetaDeCredito> TarjetaDeCredito { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitularExtensiones> TitularExtensiones { get; set; }
    }
}
