//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        public long Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public int EstadoSolicitud { get; set; }
        public long TitularId { get; set; }
        public long TarjetaDeCreditoId { get; set; }
        public long PuntoDeVentaId { get; set; }
        public string ServicioEstatal { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> AceptaRecibirEstadoCuentaEnCorreoElectronico { get; set; }
        public System.Guid RowId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public Nullable<System.Guid> ChangedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClienteTitular ClienteTitular { get; set; }
        public virtual Firmas Firmas { get; set; }
        public virtual Fotos Fotos { get; set; }
        public virtual PuntosDeVentas PuntosDeVentas { get; set; }
        public virtual TarjetaDeCredito TarjetaDeCredito { get; set; }
    }
}
